### ISSUE TITLE
一个关于代码细节的问题

### ISSUE THREAD

**Issue by guoyage** [libai1943/CartesianPlanner#2]
非常感谢分享这么好的研究工作，我在阅读代码时候，发现trajectory_optimizer.cpp文件中的result = {{x - incremental[0], y - incremental[2]}, {x + incremental[1], y + incremental[3]}}的这行代码，更改为result = {{x - incremental[0]-radius, y - incremental[2]-radius}, {x + incremental[1]+radius, y + incremental[3]+radius}};是否更为合适？？感谢您的解答

**Comment by yakunouyang** [comment]
隧道框判定与边界无碰撞之后，各个方向要再收缩圆盘半径`radius`，才能得到圆盘中心点的的行驶区域，所以返回的那一行没有再加上`radius`。

To get the actual feasible driving corridor for dual-disc center, the corridor box must shrink `radius` to make sure that generated discs does not collide with the boundary, so the returned box does not have `radius` added to it, for detailed explaination please refer to our paper.
